name: root
dependencies:
- _license=1.1=py34_1
- abstract-rendering=0.5.1=np19py34_0
- alabaster=0.7.6=py34_0
- anaconda=2.4.1=np110py34_0
- anaconda-client=1.2.1=py34_0
- appnope=0.1.0=py34_0
- appscript=1.0.1=py34_0
- argcomplete=1.0.0=py34_1
- astropy=1.0.4=np19py34_0
- babel=2.1.1=py34_0
- backports_abc=0.4=py34_0
- basemap=1.0.7=np19py34_0
- bcolz=0.11.3=py34_0
- beautiful-soup=4.3.2=py34_0
- beautifulsoup4=4.4.1=py34_0
- binstar=0.12=2
- bitarray=0.8.1=py34_0
- blaze-core=0.9.0=py34_0
- blz=0.6.2=np19py34_1
- bokeh=0.11.0=py34_1
- boto=2.38.0=py34_0
- bottleneck=1.0.0=np19py34_0
- certifi=2015.9.6.2=py34_0
- cffi=1.2.1=py34_0
- clyent=1.2.0=py34_0
- colorama=0.3.3=py34_0
- conda=3.19.0=py34_0
- conda-build=1.18.2=py34_0
- conda-env=2.4.5=py34_0
- configobj=5.0.6=py34_0
- cryptography=1.0.2=py34_0
- curl=7.43.0=1
- cycler=0.9.0=py34_0
- cython=0.23.4=py34_1
- cytoolz=0.7.4=py34_0
- datashape=0.5.0=py34_0
- decorator=4.0.6=py34_0
- docutils=0.12=py34_0
- dynd-python=0.6.5=np19py34_0
- et_xmlfile=1.0.1=py34_0
- fastcache=1.0.2=py34_0
- flask=0.10.1=py34_1
- freetype=2.5.5=0
- funcsigs=0.4=py34_0
- future=0.15.2=py34_0
- gdal=2.0.0=np19py34_0
- geos=3.3.3=0
- graphviz=2.38.0=0
- greenlet=0.4.9=py34_0
- h5py=2.5.0=np19py34_3
- hdf5=1.8.15.1=2
- idna=2.0=py34_0
- ipykernel=4.2.2=py34_0
- ipython=4.0.2=py34_0
- ipython-notebook=4.0.4=py34_0
- ipython-qtconsole=4.0.1=py34_0
- ipython_genutils=0.1.0=py34_0
- ipywidgets=4.1.1=py34_0
- itsdangerous=0.24=py34_0
- jbig=2.1=0
- jdcal=1.2=py34_0
- jedi=0.9.0=py34_0
- jinja2=2.8=py34_0
- jpeg=8d=1
- jsonschema=2.4.0=py34_0
- jupyter=1.0.0=py34_1
- jupyter_client=4.1.1=py34_0
- jupyter_console=4.0.3=py34_0
- jupyter_core=4.0.6=py34_0
- krb5=1.13.2=0
- launcher=1.0.0=3
- libdynd=0.6.5=0
- libgdal=2.0.0=0
- libnetcdf=4.3.3.1=1
- libpng=1.6.17=0
- libsodium=1.0.3=0
- libtiff=4.0.6=1
- libxml2=2.9.2=0
- libxslt=1.1.28=2
- llvmlite=0.8.0=py34_0
- lxml=3.5.0=py34_0
- markupsafe=0.23=py34_0
- matplotlib=1.4.3=np19py34_3
- mistune=0.7.1=py34_0
- mock=1.3.0=py34_0
- multipledispatch=0.4.8=py34_0
- nbconvert=4.1.0=py34_0
- nbformat=4.0.1=py34_0
- netcdf4=1.1.9=np19py34_0
- networkx=1.10=py34_0
- nltk=3.1=py34_0
- node-webkit=0.10.1=0
- nose=1.3.7=py34_0
- notebook=4.1.0=py34_0
- numba=0.23.0=np19py34_0
- numexpr=2.4.4=np19py34_0
- numpy=1.9.3=py34_0
- odo=0.4.0=py34_0
- openpyxl=2.3.2=py34_0
- openssl=1.0.1k=1
- pandas=0.16.2=np19py34_0
- path.py=8.1.2=py34_1
- patsy=0.4.0=np19py34_0
- pbr=1.3.0=py34_0
- pep8=1.6.2=py34_0
- pexpect=3.3=py34_0
- pickleshare=0.5=py34_0
- pillow=3.1.0=py34_0
- pip=7.1.2=py34_0
- ply=3.8=py34_0
- psutil=3.3.0=py34_0
- ptyprocess=0.5=py34_0
- py=1.4.30=py34_0
- pyasn1=0.1.9=py34_0
- pycosat=0.6.1=py34_0
- pycparser=2.14=py34_0
- pycrypto=2.6.1=py34_0
- pycurl=7.19.5.1=py34_2
- pyflakes=1.0.0=py34_0
- pygments=2.0.2=py34_0
- pyopenssl=0.15.1=py34_1
- pyparsing=2.0.3=py34_0
- pyqt=4.11.4=py34_1
- pytables=3.2.2=np19py34_0
- pytest=2.8.1=py34_0
- python=3.4.3=0
- python-dateutil=2.4.2=py34_0
- python.app=1.2=py34_4
- pytz=2015.7=py34_0
- pyyaml=3.11=py34_1
- pyzmq=15.2.0=py34_0
- qt=4.8.7=1
- qtconsole=4.1.1=py34_0
- readline=6.2=2
- redis=2.6.9=0
- redis-py=2.10.3=py34_0
- requests=2.9.1=py34_0
- rope=0.9.4=py34_1
- runipy=0.1.3=py34_0
- scikit-image=0.11.3=np19py34_0
- scikit-learn=0.16.1=np19py34_0
- scipy=0.16.0=np19py34_1
- seaborn=0.6.0=np19py34_0
- setuptools=19.2=py34_0
- simplegeneric=0.8.1=py34_0
- sip=4.16.9=py34_0
- six=1.10.0=py34_0
- snowballstemmer=1.2.0=py34_0
- sockjs-tornado=1.0.1=py34_0
- sphinx=1.3.1=py34_0
- sphinx_rtd_theme=0.1.7=py34_0
- spyder=2.3.8=py34_0
- spyder-app=2.3.8=py34_0
- sqlalchemy=1.0.11=py34_0
- sqlite=3.9.2=0
- statsmodels=0.6.1=np19py34_0
- sympy=0.7.6.1=py34_0
- terminado=0.5=py34_1
- tk=8.5.18=0
- toolz=0.7.4=py34_0
- tornado=4.3=py34_0
- traitlets=4.0.0=py34_0
- ujson=1.33=py34_0
- unicodecsv=0.14.1=py34_0
- werkzeug=0.11.3=py34_0
- wheel=0.26.0=py34_1
- xlrd=0.9.4=py34_0
- xlsxwriter=0.8.2=py34_0
- xlwings=0.6.4=py34_0
- xlwt=1.0.0=py34_0
- xonsh=0.2.3=py34_0
- xz=5.0.5=0
- yaml=0.1.6=0
- zeromq=4.1.3=0
- zlib=1.2.8=0
- pip:
  - ansi==0.1.3
  - backports-abc==0.4
  - blaze==0.9.0
  - bottle==0.12.8
  - chatterbot==0.2.6
  - colorlog==2.6.0
  - daemonize==2.3.1
  - dnspython3==1.12.0
  - docopt==0.6.2
  - err==3.0.5
  - et-xmlfile==1.0.1
  - fuzzywuzzy==0.7.0
  - ipython-genutils==0.1.0
  - jsondatabase==0.0.6
  - jupyter-client==4.1.1
  - jupyter-console==4.0.3
  - jupyter-core==4.0.6
  - markdown==2.6.2
  - oauthlib==1.0.3
  - pcse==5.1.1
  - pinggraph==0.0.11
  - plotly==1.9.3
  - profilehooks==1.8.1
  - prompt-toolkit==0.56
  - ptpython==0.27
  - pygments-markdown-lexer==0.1.0.dev39
  - pymongo==3.0.3
  - python-levenshtein==0.12.0
  - pyvim==0.0.12
  - qgrid==0.2.0
  - requests-oauthlib==0.5.0
  - rope-py3k-0.9.4==1
  - sphinx-rtd-theme==0.1.7
  - tables==3.2.2
  - tabulate==0.7.5
  - tqdm==3.4.0
  - waitress==0.8.10
  - wcwidth==0.1.5
  - webob==1.5.0
  - webtest==2.0.18
  - yapsy==1.11.223

